run:
  timeout: 5m
  go: "1.24.5"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - gocritic
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G101 # Look for hardcoded credentials
      - G102 # Bind to all interfaces
      - G104 # Errors unhandled
      - G107 # Url provided to HTTP request as taint input
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G303 # Creating tempfile using a predictable path
      - G304 # File path provided as taint input
      - G305 # File traversal when extracting zip archive
      - G306 # Poor file permissions used when writing to a file
      - G307 # Poor file permissions used when creating a file
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
      - G501 # Import blocklist: crypto/md5
      - G502 # Import blocklist: crypto/des
      - G503 # Import blocklist: crypto/rc4
      - G504 # Import blocklist: net/http/cgi
      - G505 # Import blocklist: crypto/sha1

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
        - dupl
        - gocritic
    - path: vendor/
      linters:
        - all
    - path: cmd/docs/
      linters:
        - all
    - path: cmd/playground/
      linters:
        - all 