version: '3.8'

services:
  test-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkatype_test
    # Порты не публикуем — тесты запускаются внутри общей сети docker compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data

  tester:
    image: golang:1.24
    depends_on:
      test-db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: test-db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkatype_test
      MAIL_SERVER: smtp.test.com
      MAIL_PORT: "587"
      MAIL_ADDRESS: test@example.com
      MAIL_PASSWORD: test_password
      TEST_MODE: "true"
    command: ["/bin/sh", "-lc", "/usr/local/go/bin/go env && /usr/local/go/bin/go version && /usr/local/go/bin/go test ./... -v"]

volumes:
  test_db_data: 