openapi: 3.0.3
info:
  title: LINKa Type API Gateway
  version: 0.1.0
x-yc-apigateway:
  service_account_id: "{{SERVICE_ACCOUNT_ID}}"
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /admin:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /admin/:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /assets/{file}:
    parameters:
      - name: file
        in: path
        required: true
        schema:
          type: string
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /client.md:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /AGENTS.md:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /healthz:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
      responses:
        "200":
          description: OK
  /v1/auth:
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
      responses:
        "200":
          description: OK
  /v1/predictor:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
        omitEmptyHeaders: true
      responses:
        "200":
          description: OK
  /v1/admin/stats:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/admins:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/admins/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    delete:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: DELETE
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/client-keys:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/client-keys/{key_hash}:
    parameters:
      - name: key_hash
        in: path
        required: true
        schema:
          type: string
    delete:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: DELETE
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/global/categories:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/global/categories/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    patch:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: PATCH
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    delete:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: DELETE
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/factory/questions:
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/admin/factory/questions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    patch:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: PATCH
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    delete:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: DELETE
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
  /v1/{path}:
    parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
    get:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: GET
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: POST
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    put:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: PUT
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    patch:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: PATCH
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    delete:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: DELETE
        headers:
          Authorization: "$request.header.Authorization"
      responses:
        "200":
          description: OK
    options:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "{{CORE_API_CONTAINER_ID}}"
        service_account_id: "{{SERVICE_ACCOUNT_ID}}"
        httpMethod: OPTIONS
      responses:
        "200":
          description: OK

