name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run E2E tests with Docker Compose
      run: |
        docker compose --profile test build
        docker compose --profile test up --abort-on-container-exit --exit-code-from e2e-tests
      env:
        JWT_SECRET: test-jwt-secret-for-ci
        JWT_ISSUER: test-issuer
        JWT_AUDIENCE: test-audience
        MAIL_SERVER: smtp.test.com
        MAIL_PORT: 587
        MAIL_ADRESS: test@example.com
        MAIL_PASSWORD: test_password
        TEST_MODE: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: test-results/
        retention-days: 30
